apiVersion: apps/v1
kind: Deployment
metadata: 
  name: fe-deploy
  labels:
    app: frontend
    environment: prod
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      environment: prod
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: frontend
        environment: prod
      name: nginx-pod
    spec: 
      containers:
        - name: frontend-cont
          image: nginx
          ports:
            - containerPort: 80




