apiVersion: v1
kind: Service
metadata:
  name: fe-service
  labels:
    app: frontend
    environment: prod
spec:
  selector: 
    app: frontend
  type: NodePort
  ports:
      - nodePort: 32556
        port: 80
        targetPort: 80

