apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-deployment
  labels: 
    app: jenkins
spec:
  minReadySeconds: 20      
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: jenkins
        environment: production
        version: "2.X"
    spec:
      containers:
        - name: jenkins
          image: jenkins:2.60.3
          ports:
            - containerPort: 8080
              protocol: TCP

