apiVersion: v1
kind: Pod
metadata: 
  name: testing-pod
  labels:
    app: alpine
spec:
  containers: 
    - name: alpine
      image: alpine
      args:
        - /bin/sh
        - -c
        - sleep 1d          
