apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
  labels:
    app: volume
    environment: prod
spec:
  containers:
    - image: alpine
      name: volume
      args: 
        - /bin/sh
        - -c
        - sleep 1d
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          name: data-volume
        - mountPath: /var/log
          name: logs-volume
  volumes:
    - name: data-volume
      emptyDir: {}
    - name: logs-volume
      emptyDir: {}

