apiVersion: v1
kind: Pod
metadata: 
  name: hellopod
spec: 
  containers:
    - image: httpd
      name: httpdcont
      ports: 
        - containerPort: 80
    - image: mysql:5.7
      name: mysqlcont
      ports:
        - containerPort: 3306  
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: 'admin@123'   
