apiVersion: v1
kind: PersistentVolume
metadata: 
  name: hello-pv
spec: 
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath:  
    path: /var/log
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem 
