apiVersion: v1
kind: Pod
metadata: 
  name: hello-pod
spec: 
  containers:
    - args:
        - /bin/sh
        - -c
        - sleep 60s
      image: alpine
      name: alpine-pod
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /var/log
          name: pv-storage
  volumes:
    - persistentVolumeClaim:
        claimName: hello-pvc
      name: pv-storage   


