apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: replicas-demo
  labels:
    app: httpd
spec:
  minReadySeconds: 5      
  replicas: 2
  selector: 
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - image: nginx
          name: httpd-cont
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5     



